### ISSUE TITLE
Incorrect macOS dylibs

### ISSUE THREAD

**Issue by IsaacMarovitz** [HexaEngine/HexaEngine.ImGui#3]
The files labelled as `dylib`s for macOS are actually just Windows DLLs, these should be made real dynamic libraries.

**Comment by JunaMeinhold** [comment]
Thanks for pointing that out, I hadn't realised. I tried compiling from a Windows machine, but it seems that each file is just a Windows DLL. I'll recompile and check them, and I'll upload a fix soon. So, if you don't mind, could you check it if you have a macOS machine (because I don't have one)?

**Comment by JunaMeinhold** [comment]
Edit: I have uploaded a fix.

**Comment by IsaacMarovitz** [comment]
x86 files look correct, but I saw that ARM binaries were removed, these should be added back

**Comment by JunaMeinhold** [comment]
I'm having trouble cross-compiling to arm64. I'll look into it today.

**Comment by JunaMeinhold** [comment]
Hey little update, I don't know how to compile it, the clang compiler is failing and I don't know how to set up osxcross. It might take me some time to get it working. Could you maybe compile it if it's possible, you can find the cmake projects in https://github.com/HexaEngine/HexaEngine.Native, just make sure to clone it recursively so the sub-modules are cloned too.

**Comment by IsaacMarovitz** [comment]
<img width="1272" alt="Screenshot 2024-01-25 at 15 51 31" src="https://github.com/HexaEngine/HexaEngine.ImGui/assets/42140194/413d2de0-e017-474d-a802-3741fb5a34aa">

Seems like I'm missing some headers or something

**Comment by JunaMeinhold** [comment]
Try using
cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -S ./ -B ./build
cmake --build ./build --config Release

**Comment by IsaacMarovitz** [comment]
No change

**Comment by JunaMeinhold** [comment]
Strange, check if ImGui is cloned into the sub-dir correctly.

**Comment by IsaacMarovitz** [comment]
<img width="1032" alt="Screenshot 2024-01-25 at 16 40 16" src="https://github.com/HexaEngine/HexaEngine.ImGui/assets/42140194/34f3e56f-9d8d-4bf7-a584-fcdb87cb1183">

Seems correct

**Comment by JunaMeinhold** [comment]
Oh wait in the cimgui.h there is a macro that you need to add manually if it's not there

#define CIMGUI_DEFINE_ENUMS_AND_STRUCTS

**Comment by IsaacMarovitz** [comment]
<img width="1122" alt="Screenshot 2024-01-25 at 16 50 46" src="https://github.com/HexaEngine/HexaEngine.ImGui/assets/42140194/66a5a0df-528c-4301-8c8d-a9bf671c3f28">

Now I'm getting redefinition errors 😆

**Comment by JunaMeinhold** [comment]
Try this https://drive.google.com/file/d/1UkXNZhNjd9UJ55uMRH7w63X1FBPjb-4p/view?usp=drive_link
I can't push the changes on git

**Comment by IsaacMarovitz** [comment]
[dylibs.zip](https://github.com/HexaEngine/HexaEngine.ImGui/files/14058214/dylibs.zip)

That worked!
